name: my first workflow
on: workflow_dispatch

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print a message
        run: echo "Hello World b17 from github actions"

      - name: do a calculation
        run: echo $((10 + 987))

      - name: check the version of os on runner
        run: cat /etc/os-release
