name: my first workflow
on: push

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: putting code on the runner
        run: git clone https://github.com/nikhil07rao-del/Github-Actions-.git

      - name: checking out the code
        run: |
          cd Github-Actions-
          ls -la
          chmod +x new.sh
          ./new.sh
